# Generated by Django 4.0.6 on 2022-09-06 19:19

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_collection_product_collection'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='snippet',
            field=models.CharField(default='Snippet', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='subname',
            field=models.CharField(default='Subname', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
