# Generated by Django 4.0.6 on 2022-09-06 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_description_product_snippet_product_subname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='snippet',
            field=models.CharField(default='Snippet', max_length=250, null=True),
        ),
    ]
