# Generated by Django 4.0.6 on 2022-09-07 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_collection_image_alter_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('view', models.ImageField(blank=True, null=True, upload_to='images/products/versions')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='versions',
            field=models.ManyToManyField(related_name='versions', to='store.version'),
        ),
    ]
