# Generated by Django 4.0.6 on 2022-09-07 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_version_product_versions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name_plural': 'Order Items'},
        ),
        migrations.AlterModelOptions(
            name='shippingaddress',
            options={'verbose_name_plural': 'Shipping Addresses'},
        ),
        migrations.AlterModelOptions(
            name='version',
            options={'verbose_name_plural': 'Product Versions'},
        ),
        migrations.RenameField(
            model_name='version',
            old_name='view',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='versions',
        ),
        migrations.AddField(
            model_name='version',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.product'),
        ),
    ]
