# Generated by Django 4.0.6 on 2022-09-07 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_orderitem_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='images/default/default_product.png', null=True, upload_to='images/products/'),
        ),
    ]
