# Generated by Django 4.0.6 on 2022-09-13 06:13

from django.db import migrations, models
import django.db.models.deletion
import store.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_alter_profile_bio'),
        ('store', '0010_collection_description_alter_product_collection'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rating_manual',
            field=store.models.DecimalRangeField(decimal_places=1, default=4.3, max_digits=2),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', store.models.DecimalRangeField(decimal_places=1, default=4.3, max_digits=2)),
                ('review', models.CharField(max_length=200, null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.profile')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.product')),
            ],
            options={
                'verbose_name_plural': 'Reviews',
            },
        ),
    ]
