# Generated by Django 4.0.6 on 2022-08-17 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_title_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='meta_tag',
            field=models.CharField(default='kaavi', max_length=255),
        ),
    ]
