# Generated by Django 4.0.6 on 2022-09-03 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='display',
            field=models.ImageField(blank=True, null=True, upload_to='images/profile/'),
        ),
    ]
