# Generated by Django 4.0.6 on 2022-09-04 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_alter_post_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
        migrations.AddField(
            model_name='post',
            name='categora',
            field=models.TextField(default='This is text'),
        ),
    ]
