# Generated by Django 4.0.6 on 2022-09-05 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_post_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='categora',
        ),
    ]
