# Generated by Django 4.0.6 on 2022-09-07 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_remove_post_categora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='display',
            field=models.ImageField(blank=True, null=True, upload_to='images/categories/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='header_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/posts/'),
        ),
    ]
