# Generated by Django 4.0.6 on 2022-09-15 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_rename_profile_profiler'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profiler',
            name='user',
        ),
    ]
